apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting-app

resources:
  - namespace.yaml
  - configmap.yaml
  - redis-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - hpa.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
